# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_identifier', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('item_serial_id', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchased', models.PositiveIntegerField(default=0)),
                ('returned', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='On_Sale',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_active_date', models.DateField()),
                ('last_active_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentStore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintTagItems',
            fields=[
                ('requirements', models.CharField(choices=[('total price', 'total price'), ('item price', 'item price'), ('category', 'category'), ('select', 'select'), ('all', 'all')], max_length=20)),
                ('price', models.PositiveIntegerField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTag',
            fields=[
                ('lookup_code', models.CharField(default='n11c23sw1k', editable=False, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_price', models.PositiveIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('elapse_days', models.PositiveIntegerField()),
                ('holiday_elapse_days', models.PositiveIntegerField()),
                ('apply_to_sales', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnTag',
            fields=[
                ('verified', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('c_score', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lookup_code', models.CharField(default='r43q68eu9x', editable=False, max_length=10)),
                ('employee_processing_return', models.ManyToManyField(blank=True, to='product.Employee')),
                ('purchase_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.PurchaseTag')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('min_c_score', models.PositiveIntegerField()),
                ('api_code', models.CharField(default='1w9vgd9chk3cbiix6n6q8u1a6', editable=False, max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit'), ('check', 'check')], default='cash', max_length=10)),
                ('last_4', models.PositiveIntegerField(null=True)),
                ('returned', models.BooleanField(default=False)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Employee')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store')),
            ],
        ),
        migrations.AddField(
            model_name='returntag',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='returnpolicy',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='returned',
            name='items_returned',
            field=models.ManyToManyField(to='product.ReturnTag'),
        ),
        migrations.AddField(
            model_name='purchasetag',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='purchasetag',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Transaction'),
        ),
        migrations.AddField(
            model_name='printtagitems',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='on_sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.On_Sale'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
        migrations.AddField(
            model_name='category',
            name='return_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ReturnPolicy'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Store'),
        ),
    ]
